### ISSUE TITLE
How to Improve Performance?

### ISSUE THREAD

**Issue by UmerIftikhar** [juffalow/express-graphql-example#13]
Hey, Thanks a lot for the wonderful project.
But I have some reservations, hope you could address them.

```
query{
  authors{
    name
    last_name
      quotes{
        id
        quote
      }
  }
}
```
**_Query_** like above will have performance issues, since numerous requests are made to the Database.
**Example:**  

```
Executing (default): SELECT [id], [name], [last_name] FROM [author] AS [author];
Executing (default): SELECT [id], [name], [last_name] FROM [author] AS [author];
Executing (default): SELECT [id], [name], [last_name] FROM [author] AS [author];
Executing (default): SELECT [id], [name], [last_name] FROM [author] AS [author];
Executing (default): SELECT [id], [author_id], [quote] FROM [quote] AS [quote] WHERE [quote].[author_id] = 1;
Executing (default): SELECT [id], [author_id], [quote] FROM [quote] AS [quote] WHERE [quote].[author_id] = 2;
Executing (default): SELECT [id], [author_id], [quote] FROM [quote] AS [quote] WHERE [quote].[author_id] = 3;
Executing (default): SELECT [id], [author_id], [quote] FROM [quote] AS [quote] WHERE [quote].[author_id] = 4;
Executing (default): SELECT [id], [author_id], [quote] FROM [quote] AS [quote] WHERE [quote].[author_id] = 5;
Executing (default): SELECT [id], [author_id], [quote] FROM [quote] AS [quote] WHERE [quote].[author_id] = 6;
```

So, rather than querying DB once, n+1 requests are made.
One to retrieve all the users and n to retrieve _quotes_ for each of the _author_.
Do you have any recommendations how to improve that and minimize the number of SQL round-trips?

**Comment by juffalow** [comment]
Hi, yes I know about this issue. I solved it in another project and forgot about it here.

The problem is in *types/author.js* file:

```javascript
// graphql/types/author.js
// ...
  quotes: {
    type: new GraphQLList(Quote),
    description: "author's quotes",
    resolve(author) {
      return models.quote.findAll({ where: { author_id: author.id } });
    }
  }
// ...
```

Here you can see that `quotes` are always loading from the database. So the solution is in updating authors query to load the quotes and than update the author type to check if it is already loaded or not.

The authors query now:

```javascript
// graphql/queries/author/author.js
// ...
  resolve(root, args) {
    const offset = args.offset || 0;
    const limit = args.first || 10;
    delete args.offset;
    delete args.first;
    return models.author.findAll({where: args, offset, limit});
  }
// ...
```

Here, you need to say to sequelize to load the quotes also.

```javascript
// graphql/queries/author/author.js
// ...
    return models.author.findAll({where: args, include: [ { model: models.quote } ], offset, limit});
// ...
```

Now, you load the quotes but the resolve function in author type will load them again. To prevent this, check if they are already loaded:

```javascript
// graphql/types/author.js
// ...
  quotes: {
      type: new GraphQLList(Quote),
      description: "author's quotes",
      resolve(author) {
          if (author.hasOwnProperty('quotes')) {
            return author.quotes;
          }
          return models.quote.findAll({ where: { author_id: author.id } });
      }
  }
// ...
```

**I do not know if this is valid solution, but it works.**

Now, it will do only one SQL query to the database. Problem is, you are loading quotes even if they are not required to be loaded. There should be some better solution to first check if the user requires to load the associated models or not.

And if you forgot somewhere to load the associated model, it does not matter. You check if it has the property, and if not, the fallback is to load it from the DB.

**Comment by juffalow** [comment]
Ok, it seems like there is the information which values the user requested. According to the [docs](
https://graphql.org/learn/execution/#root-fields-resolvers) the resolve function should look like this:

```javascript
// graphql/queries/author/author.js
// ...
  resolve(obj, args, context, info) {
    // ...
  }
// ...
```

In the info object, you can get the information about the query. Then you are able to load the associated model(s) based on what the user requested. With this, you can optimize the DB queries even more.

**Comment by juffalow** [comment]
The problem is still there for the quote and author query.
